Repository PromptPlace/PromtPlace-FE, pull requests merged in 2025-07, with the labels that each got.

#8 [Feat] 프롬프트 TIP 및 공지사항 UI 작성
  package.json
  pnpm-lock.yaml
  src/pages/PromptGuidePage/PromptGuideDetailPage.tsx
  src/pages/PromptGuidePage/PromptGuidePage.tsx
  src/pages/PromptGuidePage/components/Pagination.tsx
  src/pages/PromptGuidePage/img/Facebook.svg
  src/pages/PromptGuidePage/img/Frame 298.svg
  src/pages/PromptGuidePage/img/instagram.svg
  src/pages/PromptGuidePage/img/kakao_talk.svg
  src/pages/PromptGuidePage/img/linkhub logo.svg
Labels: :sparkles: Feat

#13 [Feat] 메시지함 & 알림 UI 작성
  pnpm-lock.yaml
  src/assets/icon-mail-notread.svg
  src/assets/icon-mail-read.svg
  src/pages/MyPage/MyMessageDetailPage.tsx
  src/pages/MyPage/MyMessagePage.tsx
  src/pages/MyPage/components/MessagePagination.tsx
  src/pages/MyPage/components/NotificationPagination.tsx
Labels: :sparkles: Feat

#20 [Feat] 프롬프트 상세보기, 신고하기
  src/components/Button/TagButton.tsx
  src/layouts/HomeLayout.tsx
  src/pages/PromptDetailPage/PromptDetailPage.tsx
  src/pages/PromptDetailPage/assets/profile.jpg
  src/pages/PromptDetailPage/assets/sample1.png
  src/pages/PromptDetailPage/assets/sample2.png
  src/pages/PromptDetailPage/components/PromptActions.tsx
  src/pages/PromptDetailPage/components/PromptHeader.tsx
  src/pages/PromptDetailPage/components/PromptInfo.tsx
  src/pages/PromptDetailPage/components/ReportModal.tsx
  src/pages/PromptDetailPage/components/ReviewList.tsx
  src/pages/PromptDetailPage/components/UpdateModal.tsx
Labels: :sparkles: Feat

#23 [Feat] 헤더, 사이드바 구현
  src/assets/icon-sidebar-BiReceipt.svg
  src/assets/icon-sidebar-FiLogOut.svg
  src/assets/icon-sidebar-archive.svg
  src/assets/icon-sidebar-chat-bubble.svg
  src/assets/icon-sidebar-mail.svg
  src/assets/icon-sidebar-person.svg
  src/assets/img-example-profile2.jpg
  src/components/Button/IconButton.tsx
  src/components/Navbar.tsx
  src/components/Sidebar.tsx
  src/index.css
Labels: :sparkles: Feat

#28 [Feat] 내 프롬프트 페이지 UI 구현(#16)
  src/assets/icon-kebabMenu.svg
  src/components/Modal/SocialLoginModal.tsx
  src/pages/MyPage/MyMessagePage.tsx
  src/pages/MyPage/MyPromptPage.tsx
  src/pages/MyPage/components/MyPromptsTabs.tsx
  src/pages/MyPage/components/PromptCard.tsx
  src/pages/PromptDetailPage/PromptDetailPage.tsx
  src/pages/PromptDetailPage/components/PromptActions.tsx
  src/pages/PromptDetailPage/components/PromptHeader.tsx
  src/pages/PromptDetailPage/components/PromptInfo.tsx
Labels: :sparkles: Feat

#30 [Feat] 404 페이지 구현
  src/assets/icon-notfound-dots.svg
  src/assets/icon-notfound-prompt.svg
  src/assets/icon-sidebar-BiReceipt.svg
  src/assets/icon-sidebar-archive.svg
  src/assets/icon-sidebar-chat-bubble.svg
  src/assets/icon-sidebar-mail.svg
  src/assets/icon-sidebar-person.svg
  src/assets/img-notfound.png
  src/components/Button/PrimaryButton.tsx
  src/components/Sidebar.tsx
  src/index.css
  src/layouts/HomeLayout.tsx
  src/layouts/ProtectedLayout.tsx
  src/pages/NotFoundPage/NotFoundPage.tsx
  src/utils/scrollToTop.ts
Labels: :sparkles: Feat

#33 [Feat] 프롬프트 상세 다운로드 페이지 구현
  src/pages/PromptDetailPage/assets/BiSend.png
  src/pages/PromptDetailPage/components/DownloadModal.tsx
  src/pages/PromptDetailPage/components/PromptActions.tsx
  src/pages/PromptDetailPage/components/ReportModal.tsx
  src/pages/PromptDetailPage/components/ReviewList.tsx
Labels: :sparkles: Feat

#40 [Design] 프롬프트 팁, 마이페이지 메시지함 페이지 UI 수정
  src/pages/MyPage/MyMessageDetailPage.tsx
  src/pages/MyPage/MyMessagePage.tsx
  src/pages/MyPage/components/MessagePagination.tsx
  src/pages/PromptGuidePage/PromptGuideDetailPage.tsx
  src/pages/PromptGuidePage/PromptGuidePage.tsx
  src/pages/PromptGuidePage/components/Pagination.tsx
  src/pages/PromptGuidePage/img/Facebook.svg
  src/pages/PromptGuidePage/img/Frame 298.svg
  src/pages/PromptGuidePage/img/instagram.svg
  src/pages/PromptGuidePage/img/kakao_talk.svg
  src/pages/PromptGuidePage/img/linkhub logo.svg
Labels: :bug: Fix

#49 [Design] layout height 값 수정
  src/layouts/HomeLayout.tsx
  src/layouts/ProtectedLayout.tsx
Labels: 🎨 Design

#52 [Feat] PWA 자동화 설정
  index.html
  package.json
  pnpm-lock.yaml
  public/apple-touch-icon.png
  public/favicon-96x96.png
  public/favicon.ico
  public/favicon.svg
  public/favicons/site.webmanifest
  public/service-worker.js
  public/web-app-manifest-192x192.png
  public/web-app-manifest-512x512.png
  tsconfig.app.json
  vercel.json
  vite.config.ts
Labels: :sparkles: Feat

#55 [fix] 검색페이지 오류 수정
  src/pages/MainPage/MainPage.tsx
  src/pages/MainPage/SearchPage.tsx
  src/pages/MainPage/components/SearchPrompter.tsx
  src/pages/MainPage/components/filterBar.tsx
  src/pages/MainPage/components/promptCard.tsx
  src/types/prompt.ts
Labels: :bug: Fix

#60 [Feat] 프롬프트 상세 어드민 관련 페이지
  src/pages/PromptDetailPage/PromptDetailPage.tsx
  src/pages/PromptDetailPage/assets/contentcheck.png
  src/pages/PromptDetailPage/assets/deletebutton.png
  src/pages/PromptDetailPage/assets/updatebutton.png
  src/pages/PromptDetailPage/components/PromptActions.tsx
  src/pages/PromptDetailPage/components/PromptHeader.tsx
  src/pages/PromptDetailPage/components/ReviewList.tsx
Labels: :sparkles: Feat

#70 [Feat] 프롬프트 TIP & 마이페이지 메시지함 반응형 UI
  src/pages/MyPage/MyMessageDetailPage.tsx
  src/pages/MyPage/MyMessagePage.tsx
  src/pages/MyPage/components/MessagePagination.tsx
  src/pages/MyPage/components/NotificationPagination.tsx
  src/pages/PromptGuidePage/PromptGuideDetailPage.tsx
  src/pages/PromptGuidePage/PromptGuidePage.tsx
  src/pages/PromptGuidePage/components/MobileList.tsx
Labels: :sparkles: Feat, 🎨 Design
