Repository PromptPlace/PromtPlace-FE, pull requests merged in 2025-08, with the labels that each got.

#82 [Design]메인페이지 반응형 UI
  src/pages/MainPage/components/FilterDropdown.tsx
  src/pages/MainPage/components/MobileFilterModal.tsx
  src/pages/MainPage/components/MobilePrompt.tsx
  src/pages/MainPage/components/MobilePrompter.tsx
  src/pages/MainPage/components/filterBar.tsx
Labels: :bug: Fix, 🎨 Design

#95 [Fix] 공통 컴포넌트 및 프로필 홈 수정
  src/components/CoachMark.tsx
  src/components/Navbar.tsx
  src/components/TabBar.tsx
  src/hooks/useShowLoginModal.ts
  src/pages/ProfilePage/ProfilePage.tsx
  src/pages/ProfilePage/components/AskCard.tsx
Labels: :bug: Fix, 🎨 Design

#101 [Fix] 프롬프트 TIP, 프롬프트 작성하기 UI 수정
  src/pages/MyPage/components/MessagePagination.tsx
  src/pages/MyPage/components/NotificationPagination.tsx
  src/pages/PromptCreatePage/PromptCreatePage.tsx
  src/pages/PromptCreatePage/components/ImageList.tsx
  src/pages/PromptCreatePage/components/MobileUploadModal.tsx
  src/pages/PromptCreatePage/components/UploadModal.tsx
  src/pages/PromptGuidePage/PromptGuidePage.tsx
  src/pages/PromptGuidePage/components/MobileList.tsx
Labels: :bug: Fix, 🎨 Design

#104 [Design] qa 프롬프트 상세페이지 수정
  package.json
  pnpm-lock.yaml
  src/pages/PromptDetailPage/PromptDetailPage.tsx
  src/pages/PromptDetailPage/components/PromptActions.tsx
  src/pages/PromptDetailPage/components/ReviewList.tsx
  src/pages/PromptDetailPage/components/UpdateModal.tsx
Labels: 🎨 Design

#103 [Fix] axiosInstance 수정
  src/apis/axios.ts
Labels: :bug: Fix

#106 [Feat] 메인페이지 QA
  src/assets/icon-arrow-blue.svg
  src/assets/icon-arrow-right-blue.svg
  src/assets/icon-cancel-gray.svg
  src/assets/icon-cancle-gray.svg
  src/pages/MainPage/MainPage.tsx
  src/pages/MainPage/components/MobileFilterBar.tsx
  src/pages/MainPage/components/MobileFilterModal.tsx
  src/pages/MainPage/components/MobileFilterTab.tsx
  src/pages/MainPage/components/MobileModelTab.tsx
  src/pages/MainPage/components/MobilePrompt.tsx
  src/pages/MainPage/components/MobilePrompter.tsx
  src/pages/MainPage/components/MobileTagTab.tsx
  src/pages/MainPage/components/filterBar.tsx
  src/pages/MainPage/components/promptCard.tsx
  src/pages/MainPage/components/prompterBar.tsx
  src/pages/MainPage/dummyData.ts
Labels: :bug: Fix, 🎨 Design

#107 [Feat] 마이페이지 UI 수정
  src/components/Modal/SocialLoginModal.tsx
  src/pages/MyPage/MyPromptPage.tsx
  src/pages/MyPage/components/AccountEditForm.tsx
  src/pages/MyPage/components/ArrowIcon.tsx
Labels: :bug: Fix, :recycle: Refactor

#109 [Feat] 마이페이지 메시지 함 & 알림함 API 연동
  src/pages/MyPage/MyMessageDetailPage.tsx
  src/pages/MyPage/MyMessagePage.tsx
  src/pages/MyPage/components/MessagePagination.tsx
  src/pages/MyPage/components/NotificationPagination.tsx
Labels: :sparkles: Feat

#111 [Feat] 프로필 홈 api 중간 머지
  package.json
  pnpm-lock.yaml
  src/App.tsx
  src/apis/ProfilePage/history.ts
  src/apis/ProfilePage/inquiry.ts
  src/apis/ProfilePage/profile.ts
  src/apis/ProfilePage/sns.ts
  src/hooks/mutations/ProfilePage/useDeleteHistories.ts
  src/hooks/mutations/ProfilePage/useDeleteSNS.ts
  src/hooks/mutations/ProfilePage/usePatchDeletePrompts.ts
  src/hooks/mutations/ProfilePage/usePatchEditMember.ts
  src/hooks/mutations/ProfilePage/usePatchHistories.ts
  src/hooks/mutations/ProfilePage/usePatchReadInquiries.ts
  src/hooks/mutations/ProfilePage/usePatchSNS.ts
  src/hooks/mutations/ProfilePage/usePostEditIntro.ts
  src/hooks/mutations/ProfilePage/usePostHistories.ts
  src/hooks/mutations/ProfilePage/usePostInquiries.ts
  src/hooks/mutations/ProfilePage/usePostReplyInquiries.ts
  src/hooks/mutations/ProfilePage/usePostSNS.ts
  src/hooks/queries/ProfilePage/useGetDetailInquiries.ts
  src/hooks/queries/ProfilePage/useGetFollower.ts
  src/hooks/queries/ProfilePage/useGetFollowing.ts
  src/hooks/queries/ProfilePage/useGetHistories.ts
  src/hooks/queries/ProfilePage/useGetInquiries.ts
  src/hooks/queries/ProfilePage/useGetMember.ts
  src/hooks/queries/ProfilePage/useGetPrompts.ts
  src/hooks/queries/ProfilePage/useGetSNS.ts
  src/pages/MyPage/MyPage.tsx
  src/pages/ProfilePage/ProfilePage.tsx
  src/pages/ProfilePage/components/PromptCard.tsx
  src/pages/ProfilePage/components/RecordCard.tsx
  src/pages/ProfilePage/components/SnsCard.tsx
  src/types/ProfilePage/history.ts
  src/types/ProfilePage/inquiry.ts
  src/types/ProfilePage/profile.ts
  src/types/ProfilePage/sns.ts
Labels: :sparkles: Feat

#114 [Feat] : 프롬프트 업로드 페이지 API 연동 완료
  src/pages/PromptCreatePage/PromptCreatePage.tsx
Labels: :sparkles: Feat

#116 [Fix] 전역변수 user 타입 변경(#92)
  src/context/AuthContext.tsx
  src/pages/MyPage/MyPromptPage.tsx
Labels: :bug: Fix

#117 [Feat] 프롬프트 조회/검색 API 연동
  src/apis/MainPage/prompt.ts
  src/apis/MainPage/prompter.ts
  src/assets/icon-arrow-down-white.svg
  src/assets/icon-x-button.svg
  src/assets/img-kakao-payment.png
  src/assets/img-toss-payment.png
  src/components/Navbar.tsx
  src/constants/key.ts
  src/hooks/mutations/MainPage/usePostSearchPromptList.ts
  src/hooks/queries/MainPage/useGetPromptList.ts
  src/hooks/queries/MainPage/useGetPrompterList.ts
  src/hooks/queries/MainPage/useGetSearchList.ts
  src/pages/MainPage/MainPage.tsx
  src/pages/MainPage/SearchPage.tsx
  src/pages/MainPage/components/MobilePrompt.tsx
  src/pages/MainPage/components/MobilePrompter.tsx
  src/pages/MainPage/components/MobileTagTab.tsx
  src/pages/MainPage/components/SearchPrompter.tsx
  src/pages/MainPage/components/filterBar.tsx
  src/pages/MainPage/components/promptCard.tsx
  src/pages/MainPage/components/prompterBar.tsx
  src/pages/MainPage/dummyData.ts
  src/pages/PromptDetailPage/components/PaymentModal.tsx
  src/pages/PromptDetailPage/components/PromptActions.tsx
  src/routes/pageRoutes.tsx
  src/routes/routes.tsx
  src/types/MainPage/prompt.ts
  src/types/MainPage/prompter.ts
  src/types/prompt.ts
Labels: :sparkles: Feat

#121 [Feat] 프로필 홈 페이지 api 중간 pr
  src/apis/ProfilePage/inquiry.ts
  src/apis/ProfilePage/profile.ts
  src/components/Navbar.tsx
  src/components/Sidebar.tsx
  src/hooks/mutations/ProfilePage/useDeleteFollow.ts
  src/hooks/mutations/ProfilePage/usePatchFollow.ts
  src/hooks/mutations/ProfilePage/usePostImg.ts
  src/hooks/queries/ProfilePage/useGetDetailInquiries.ts
  src/hooks/queries/ProfilePage/useGetInquiries.ts
  src/hooks/useImgUpload.ts
  src/pages/MyPage/MyPage.tsx
  src/pages/ProfilePage/ProfilePage.tsx
  src/pages/ProfilePage/components/AskCard.tsx
  src/pages/ProfilePage/components/FollowCard.tsx
  src/pages/ProfilePage/components/InquiryDetailCard.tsx
  src/pages/ProfilePage/components/SnsCard.tsx
  src/types/ProfilePage/inquiry.ts
  src/types/ProfilePage/profile.ts
Labels: :sparkles: Feat

#119 [Feat] TIP & 공지사항 페이지 API 연동
  src/pages/PromptGuidePage/PromptGuideDetailPage.tsx
  src/pages/PromptGuidePage/PromptGuidePage.tsx
  src/pages/PromptGuidePage/components/MobileList.tsx
  src/pages/PromptGuidePage/components/Pagination.tsx
Labels: :sparkles: Feat

#126 ✨ Feat : 프롬프트 수정 페이지 API 연동 (#118)
  src/pages/PromptEdit/PromptEditPage.tsx
  src/pages/PromptEdit/components/Editer.tsx
  src/pages/PromptEdit/components/MobileUploadModal.tsx
  src/pages/PromptEdit/components/ModelDropdown.tsx
  src/pages/PromptEdit/components/PriceDropdown.tsx
  src/pages/PromptEdit/components/TagInput.tsx
  src/pages/PromptEdit/components/UploadModal.tsx
  src/pages/PromptEdit/components/test.txt
Labels: :sparkles: Feat

#128 [Feat]. 마이페이지 UI 수정
  src/components/Modal/LoginSwitchModal.tsx
  src/components/Modal/SocialLoginModal.tsx
  src/pages/MyPage/MyInfoPage.tsx
  src/pages/MyPage/MyPromptPage.tsx
  src/pages/MyPage/components/AccountEditForm.tsx
  src/pages/MyPage/components/Dropdown.tsx
  src/pages/MyPage/components/PromptCard.tsx
Labels: 🎨 Design

#127 [Feat] 리뷰 작성 별점 반영 api
  src/pages/PromptDetailPage/PromptDetailPage.tsx
  src/pages/PromptDetailPage/assets/profile.png
  src/pages/PromptDetailPage/assets/profile1.jpg
  src/pages/PromptDetailPage/components/CreateModal.tsx
  src/pages/PromptDetailPage/components/PromptActions.tsx
  src/pages/PromptDetailPage/components/PromptInfo.tsx
  src/pages/PromptDetailPage/components/ReviewList.tsx
Labels: :sparkles: Feat

#130 [Feat] 찜, 팔로우 기능 연결
  src/apis/PromptDetailPage/payments.ts
  src/hooks/mutations/MainPage/usePostSearchPromptList.ts
  src/hooks/mutations/PromptDetailPage/usePostPayment.ts
  src/pages/MainPage/MainPage.tsx
  src/pages/MainPage/components/FilterDropdown.tsx
  src/pages/MainPage/components/MobilePrompt.tsx
  src/pages/MainPage/components/MobilePrompter.tsx
  src/pages/MainPage/components/likes.tsx
  src/pages/MainPage/components/promptCard.tsx
  src/pages/MainPage/components/prompterBar.tsx
  src/pages/PromptDetailPage/components/PaymentModal.tsx
  src/pages/PromptDetailPage/components/PromptActions.tsx
  src/types/PromptDetailPage/payments.ts
Labels: :bug: Fix, :sparkles: Feat

#132 [Feat] 마이페이지 UI 수정 및 결제 관련 API 연결
  src/apis/MyPage/account.ts
  src/apis/MyPage/pay.ts
  src/components/Modal/LoginSwitchModal.tsx
  src/components/Modal/SocialLoginModal.tsx
  src/hooks/mutations/MyPage/account.ts
  src/hooks/queries/MyPage/useGetAccount.ts
  src/pages/MyPage/MyPayPage.tsx
  src/pages/MyPage/MyPaymentHistoryPage.tsx
  src/pages/MyPage/components/AccountEditForm.tsx
  src/pages/MyPage/components/PromptCard.tsx
  src/pages/MyPage/components/SalesHistoryCard.tsx
  src/types/MyPage/account.ts
Labels: :sparkles: Feat, 🎨 Design

#134 [Design] QA 2차 수정
  src/pages/MyPage/MyMessagePage.tsx
  src/pages/PromptCreatePage/PromptCreatePage.tsx
  src/pages/PromptCreatePage/components/MobileUploadModal.tsx
  src/pages/PromptCreatePage/components/ModelDropdown.tsx
  src/pages/PromptCreatePage/components/PriceDropdown.tsx
  src/pages/PromptCreatePage/components/TagInput.tsx
  src/pages/PromptCreatePage/components/UploadModal.tsx
  src/pages/PromptEdit/PromptEditPage.tsx
  src/pages/PromptEdit/components/MobileUploadModal.tsx
  src/pages/PromptEdit/components/PriceDropdown.tsx
  src/pages/PromptEdit/components/UploadModal.tsx
  src/pages/PromptGuidePage/PromptGuidePage.tsx
  src/pages/PromptGuidePage/components/Pagination.tsx
Labels: 🎨 Design

#138 [Feat] 마이페이지 UI 피드백 반영
  index.html
  src/apis/MyPage/account.ts
  src/context/AuthContext.tsx
  src/hooks/queries/MyPage/useGetAccount.ts
  src/pages/MyPage/MyAccountPage.tsx
  src/pages/MyPage/MyInfoPage.tsx
  src/pages/MyPage/MyPayPage.tsx
  src/pages/MyPage/MyPromptPage.tsx
  src/pages/MyPage/components/AccountEditForm.tsx
  src/pages/MyPage/components/Portal.tsx
  src/pages/MyPage/components/PromptCard.tsx
  src/types/MyPage/account.ts
Labels: :bug: Fix, 🎨 Design

#139 [Fix] 찜, 좋아요 QA 반영(#133)
  src/apis/MainPage/prompter.ts
  src/components/Navbar.tsx
  src/hooks/mutations/MainPage/useDeleteFollow.ts
  src/hooks/mutations/MainPage/usePatchFollow.ts
  src/hooks/queries/MainPage/useGetPrompterList.ts
  src/pages/MainPage/MainPage.tsx
  src/pages/MainPage/components/MobilePrompt.tsx
  src/pages/MainPage/components/MobilePrompter.tsx
  src/pages/MainPage/components/TagFilter.tsx
  src/pages/MainPage/components/likes.tsx
  src/pages/MainPage/components/prompterBar.tsx
  src/pages/PromptDetailPage/components/PaymentModal.tsx
  src/types/MainPage/prompter.ts
Labels: :bug: Fix

#146 [Design] qa 수정사항 프롬프트 상세보기
  src/pages/PromptDetailPage/PromptDetailPage.tsx
  src/pages/PromptDetailPage/components/CreateModal.tsx
  src/pages/PromptDetailPage/components/PromptActions.tsx
  src/pages/PromptDetailPage/components/PromptHeader.tsx
  src/pages/PromptDetailPage/components/PromptInfo.tsx
  src/pages/PromptDetailPage/components/ReviewList.tsx
  src/pages/PromptDetailPage/components/UpdateModal.tsx
  src/utils/reviewUtils.ts
Labels: 🎨 Design

#147 [Design] 핸드폰 크기 비율 수정
  src/pages/ProfilePage/ProfilePage.tsx
Labels: :sparkles: Feat

#148 [Fix] 구매 이력 있는 경우 삭제되지 않도록 수정
  src/pages/ProfilePage/ProfilePage.tsx
Labels: :bug: Fix

#158 [Feat] 프롬프트 상세 api연결 및 qa
  package.json
  pnpm-lock.yaml
  src/apis/PromptDetailPage/reviews.ts
  src/pages/PromptDetailPage/PromptDetailPage.tsx
  src/pages/PromptDetailPage/components/PromptActions.tsx
  src/pages/PromptDetailPage/components/PromptHeader.tsx
  src/pages/PromptDetailPage/components/PromptInfo.tsx
  src/types/PromptDetailPage/PromptReviewDto.ts
Labels: :sparkles: Feat, 🎨 Design

#176 [Design ] 수정 페이지 Editor 문제 수정
  src/pages/PromptCreatePage/PromptCreatePage.tsx
  src/pages/PromptEdit/PromptEditPage.tsx
  src/pages/PromptEdit/components/Editer.tsx
Labels: 🎨 Design

#189 [Fix] 프로필 페이지 QA 수정사항 반영
  src/apis/MainPage/.gitkeep
  src/apis/MyPage/.gitkeep
  src/apis/ProfilePage/.gitkeep
  src/apis/ProfilePage/inquiry.ts
  src/apis/ProfilePage/profile.ts
  src/apis/PromptDetailPage/.gitkeep
  src/assets/icon-arrow-left-blue.svg
  src/assets/icon-arrow-right-blue.svg
  src/assets/icon-bi-check-square.svg
  src/assets/mobile/icon-mobile-home.svg
  src/assets/mobile/icon-mobile-person.svg
  src/components/Navbar.tsx
  src/hooks/mutations/MainPage/.gitkeep
  src/hooks/mutations/MyPage/.gitkeep
  src/hooks/mutations/ProfilePage/.gitkeep
  src/hooks/mutations/ProfilePage/useDeleteFollow.ts
  src/hooks/mutations/ProfilePage/useDeleteInquiries.ts
  src/hooks/mutations/ProfilePage/usePatchEditIntro.ts
  src/hooks/mutations/ProfilePage/usePatchFollow.ts
  src/hooks/mutations/ProfilePage/usePostNotifications.ts
  src/hooks/mutations/PromptDetailPage/.gitkeep
  src/hooks/queries/MainPage/.gitkeep
  src/hooks/queries/MyPage/.gitkeep
  src/hooks/queries/ProfilePage/.gitkeep
  src/hooks/queries/ProfilePage/useGetNofify.ts
  src/hooks/queries/PromptDetailPage/.gitkeep
  src/index.css
  src/pages/MyPage/MyPage.tsx
  src/pages/ProfilePage/ProfilePage.tsx
  src/pages/ProfilePage/components/FollowCard.tsx
  src/pages/ProfilePage/components/InquiryCard.tsx
  src/pages/ProfilePage/components/PromptCard.tsx
  src/pages/ProfilePage/components/Select.tsx
  src/pages/ProfilePage/components/SnsCard.tsx
  src/types/MainPage/.gitkeep
  src/types/MyPage/.gitkeep
  src/types/ProfilePage/.gitkeep
  src/types/ProfilePage/inquiry.ts
  src/types/ProfilePage/profile.ts
  src/types/PromptDetailPage/.gitkeep
Labels: :bug: Fix

#190 [Fix] 문의함 queryKey 수정
  src/hooks/mutations/ProfilePage/useDeleteInquiries.ts
  src/hooks/queries/ProfilePage/useGetInquiries.ts
Labels: :bug: Fix

#191 [Feat] 사용자 이미지 연결
  src/components/Navbar.tsx
  src/components/Sidebar.tsx
  src/pages/MyPage/MyPage.tsx
  src/pages/ProfilePage/ProfilePage.tsx
  src/types/ProfilePage/profile.ts
Labels: :sparkles: Feat

#193 [Feat] 빈 화면 안내문구 관련 수정
  src/pages/MyPage/MyPayPage.tsx
  src/pages/MyPage/MyPaymentHistoryPage.tsx
  src/pages/MyPage/MyPromptPage.tsx
  src/pages/MyPage/MyReviewPage.tsx
Labels: :recycle: Refactor

#194 [Feat] 상세페이지 qa
  src/pages/PromptDetailPage/PromptDetailPage.tsx
  src/pages/PromptDetailPage/assets/back.svg
  src/pages/PromptDetailPage/components/DownloadModal.tsx
  src/pages/PromptDetailPage/components/PromptHeader.tsx
  src/pages/PromptDetailPage/components/PromptInfo.tsx
  src/pages/PromptDetailPage/components/ReportModal.tsx
  src/pages/PromptDetailPage/components/ReviewList.tsx
Labels: :sparkles: Feat

#199 [Fix] 결제페이지 수정
  src/pages/PromptDetailPage/components/PaymentModal.tsx
  src/pages/PromptDetailPage/components/PromptActions.tsx
Labels: :bug: Fix
